### ISSUE TITLE
Hacen falta servicios que implementar

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP6Entrega#16]
- Falta crear un servicio en OrderService sin parámetros de entrada para que devuelva los order de un consumer determinado del estilo orderService.findAllByConsumer() y que dentro se busque por el findByPrincipal().
- Falta crear un servicio en OrderService con un parámetro de entrada para que devuelva el order a partir de su id del estilo orderService.findOne(orderId) y que nos devuelva el Order cuyo id sea igual al orderId que se le pasa como parámetro.

**Comment by guillermo-ag-95** [comment]
- Falta un servicio de findAllByShoppingCartId(shoppingCartId) como el de storageService en ContentService. Mirar el código de ContentConsumerController
- Falta un servicio de findByConsumer sin parámetros de entrada. Es igual al homónimo de la misma clase pero el consumer lo pasamos por el findByPrincipal. Mirar el código de ShoppingCartConsumerController

**Comment by guillermo-ag-95** [comment]
Se me ha olvidado ponerlo: Todas las funcionalidades están en mi rama. No quería subirlo a Develop ya que faltan cosas. Si quieres que lo suba a Develop, responde a este issue.

**Comment by ManuelLR** [comment]
Al final esto que?

**Comment by CeuxDruman** [comment]
Solved
