### ISSUE TITLE
¡ERROR MUY RARO!

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP6Entrega#21]
Ocurrió lo siguiente:
-Como usuario no autenticado liste items
-Comentarios del item
-Creé uno nuevo
-Estando en la lista de los comentarios de nuevo di click en logout
-Me logueé como consumer
-Me llevo a la url: http://localhost:8080/Acme-Supermarket/Picture
Obviamente eso petó y me dió el clasico:
"Oops! It seems that you don't have access to this resource.
Return to index page"
........................
ME HA VUELTO A PASAR (Ahora estando con idioma en español):
-Estaba no autenticado
-Listé los Items
-Le di a loguearme
-Me loguee como admin y me llevo a la url: http://localhost:8080/Acme-Supermarket/Foto
...................................
Y OTRA VEZ
-Estaba no autenticado
-Listé los comments de un objeto tras haber creado un comment.
-Me deslogue en esa vista
-Me logueo como consumer1
-Y slte, en vez del Welcome, la url: http://localhost:8080/Acme-Supermarket/Picture

**Comment by migrodcab** [comment]
Listo @287a9c6b4809bb9e2a9a7343d0c1b40d72361535
