### ISSUE TITLE
[PREGUNTAR] Concurrencia de Delete an item from his or her shopping cart.

### ISSUE THREAD

**Issue by guillermo-ag-95** [DPIRPSG/DP6Entrega#27]
- Abro dos pestañas del mismo item desde Content.
- Lo borro desde la pestaña 1.
- Miro el listado y se ha borrado.
- Lo borro desde la pestaña 2.
- Me devuelve a la vista del carrito como en el caso anterior.

No me salta la concurrencia. Creo que debería saltar por el tema de versiones

**Comment by CeuxDruman** [comment]
Solved
