### ISSUE TITLE
Problemas al eliminar un item

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP6Entrega#6]
3 COSAS IMPORTANTES:
..........................
Al acceder como admin/admin y eliminar un item, la tabla de items se muestra sin opciones.

¿Puede ser que detecte que no sea un admin?
...................
-Borras un item
-Das a Logout
-Pete gordo!!!!
..................
Al borrar un item debe comprobar:
-ya no debe salir en las shopping cart actuales
-Sí sale en las orders tanto entregadas como no entregadas.

**Comment by migrodcab** [comment]
ya no debe salir en las shopping cart actuales --> LISTO @a3f6f72a892290c4cbf3b9bacee30d8e56ff3e18

**Comment by migrodcab** [comment]
Sí sale en las orders tanto entregadas como no entregadas. --> LISTO
