### ISSUE TITLE
double no puede ser null... ¿try catch ó Double?

### ISSUE THREAD

**Issue by CeuxDruman** [DPIRPSG/DP6Entrega#63]
Problemas y ventajas de cada opción:

OPTION 1: try catch (capturamos el tipo de excepción en concreto y nos lo saltamos devolviendo un 0 en el ratio):
Si no hay Pedidos cancelados (si ratio = 0) decimos directamente que no se puede hacer el ratio porque no hay Pedidos cancelados.

OPTION 2: Double (según Rafael C. siempre debía ser double, osea tipo primitivo):
Si lo ponemos como Double ya podemos hacer que si es 0 devuelve 0 y si es null decimos que no se puede hacer el ratio puesto que no hay orders realizadas ni canceladas este mes.

CONCLUSIONES:
1. ¿Un ratio 0/0, 1/0 y/o 0/1 (siendo 0 realmente que no hay ninguna orden cancelada/realizada) es un ratio=0 ó es que no se puede realizar el ratio?
0: OPTION 1
"message...": OPTION 2  
0/*: 0
*/0: HACERLO SOBRE EL TOTAL DE PEDIDOS (no de este mes)
2. ¿Todo tipo devuelto debe ser double como afirmó Rafael C., o sólo deben ser los que estén en la base de datos... o qué?
Siempre double: OPTION 1
Puede ser Double SIN LUGAR A DUDAS: OPTION 2

**Comment by guillermo-ag-95** [comment]
SOLUCIÓN: Buscar un Ratio lógico, valido y controlable.

**Comment by CeuxDruman** [comment]
SOLVED: Optamos por dejar que en los 3 casos no se pueda calcular el ratio indicándolo como mensaje y en el README.txt
