### ISSUE TITLE
Poca información en el fallo de las unidades a servir en el diálogo de servir orderItem

### ISSUE THREAD

**Issue by ManuelLR** [DPIRPSG/DP6Entrega#80]
No se sabe si peta porque no quedan unidades en el almacén, porque está pidiendo menos unidades o por otros motivos

**Comment by migrodcab** [comment]
Listo -> @67e287bfa98dffe984da77f77110db474fa982e4 y @9969f4fa6627ce82e049ff2e8e17830d0c898aea
